
package ariba.buyer.vsap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Ariba Web Service
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSReceiptTransfer", targetNamespace = "urn:Ariba:Buyer:vsap", wsdlLocation = "file:/C:/Users/msentissi/Documents/CLIENTS/IAM/API%20Mgmt/SOAP/WSDL_Recette/IAMSAPReceiptTransferExport_V1/Wsdl/IAMSAPReceiptTransferExport2.WSDL")
public class WSReceiptTransfer
    extends Service
{

    private final static URL WSRECEIPTTRANSFER_WSDL_LOCATION;
    private final static WebServiceException WSRECEIPTTRANSFER_EXCEPTION;
    private final static QName WSRECEIPTTRANSFER_QNAME = new QName("urn:Ariba:Buyer:vsap", "WSReceiptTransfer");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/msentissi/Documents/CLIENTS/IAM/API%20Mgmt/SOAP/WSDL_Recette/IAMSAPReceiptTransferExport_V1/Wsdl/IAMSAPReceiptTransferExport2.WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSRECEIPTTRANSFER_WSDL_LOCATION = url;
        WSRECEIPTTRANSFER_EXCEPTION = e;
    }

    public WSReceiptTransfer() {
        super(__getWsdlLocation(), WSRECEIPTTRANSFER_QNAME);
    }

    public WSReceiptTransfer(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSRECEIPTTRANSFER_QNAME, features);
    }

    public WSReceiptTransfer(URL wsdlLocation) {
        super(wsdlLocation, WSRECEIPTTRANSFER_QNAME);
    }

    public WSReceiptTransfer(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSRECEIPTTRANSFER_QNAME, features);
    }

    public WSReceiptTransfer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSReceiptTransfer(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSReceiptTransferPortType
     */
    @WebEndpoint(name = "WSReceiptTransferPortType")
    public WSReceiptTransferPortType getWSReceiptTransferPortType() {
        return super.getPort(new QName("urn:Ariba:Buyer:vsap", "WSReceiptTransferPortType"), WSReceiptTransferPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSReceiptTransferPortType
     */
    @WebEndpoint(name = "WSReceiptTransferPortType")
    public WSReceiptTransferPortType getWSReceiptTransferPortType(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Ariba:Buyer:vsap", "WSReceiptTransferPortType"), WSReceiptTransferPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSRECEIPTTRANSFER_EXCEPTION!= null) {
            throw WSRECEIPTTRANSFER_EXCEPTION;
        }
        return WSRECEIPTTRANSFER_WSDL_LOCATION;
    }

}
