
package ariba.buyer.vsap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSReceiptTransferPortType", targetNamespace = "urn:Ariba:Buyer:vsap")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSReceiptTransferPortType {


    /**
     * 
     * @param body
     * @return
     *     returns ariba.buyer.vsap.WSReceiptTransferReply
     */
    @WebMethod(operationName = "WSReceiptTransferOperation", action = "/Process Definition")
    @WebResult(name = "WSReceiptTransferReply", targetNamespace = "urn:Ariba:Buyer:vsap", partName = "body")
    public WSReceiptTransferReply wsReceiptTransferOperation(
        @WebParam(name = "WSReceiptTransferRequest", targetNamespace = "urn:Ariba:Buyer:vsap", partName = "body")
        WSReceiptTransferRequest body);

}
